import { sidebar } from "vuepress-theme-hope";

export const zh = sidebar({
  "/zh/": [
    "slide",
    {
      text: "计算机通用",
      icon: "creative",
      prefix: "universal/",
      children: [
        "lang/",
        "explain/",
        "data-structure",
        "design-patterns",
        "algorithm",
        "reg-exp",
        "character-set",
        "encrypt",
        "network",
        "architecture",
        "operating-system",
        "software-engineering",
        "test-engineering",
        "software-release",
        "technical-resources",
      ],
    },
    {
      text: "前端指南",
      icon: "creative",
      prefix: "front-end/",
      children: [
        "audition/",
        "web-h5",
        "app",
        "client",
        "mp",
        "game",
        "universal",
        "architecture",
        "development-tools",
        "faq",
      ],
    },
    {
      text: "后端指北",
      icon: "creative",
      prefix: "back-end/",
      children: [
        "audition/",
        "java",
        "nodejs",
        "system-design",
        "development-tools",
        "database",
        "search-engine",
        "distributed-dev",
        "high-performance-optimization",
        "cloud-technology",
        "big-data",
        "iot",
        "faq",
      ],
    },
    {
      text: "低码手册",
      icon: "creative",
      prefix: "lowcode/",
      children: ["product-wall/", "pan-architecture"],
    },
    {
      text: "求职与创业",
      icon: "creative",
      prefix: "careers/",
      children: [
        "plan/",
        "job-hunting",
        "recruitment",
        "communication",
        "okr-management",
        "review-summary",
      ],
    },
    {
      text: "项目精选",
      icon: "creative",
      prefix: "projects/",
      children: ["course/"],
    },
    {
      text: "书籍精选",
      icon: "creative",
      prefix: "books/",
      children: ["computer-basics/"],
    },
  ],
  "/zh/universal/": "structure",
  "/zh/front-end/": "structure",
  "/zh/back-end/": "structure",
  "/zh/lowcode/": "structure",
  "/zh/careers/": "structure",
  "/zh/projects/": "structure",
  "/zh/books/": "structure",
});
